AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with full access to S3, DynamoDB, and custom ports open

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to SSH into the instance
    Type: AWS::EC2::KeyPair::KeyName

  VpcId:
    Description: VPC Id to launch resources in
    Type: AWS::EC2::VPC::Id

  BucketEncryptionType:
    Type: String
    Description: Choose encryption for the S3 bucket
    Default: AES256
    AllowedValues:
      - AES256
      - aws:kms
      - none

  EC2DeletionPolicy:
    Type: String
    Default: Delete
    AllowedValues: [Retain, Delete]
    Description: DeletionPolicy for EC2 instance

  S3DeletionPolicy:
    Type: String
    Default: Delete
    AllowedValues: [Retain, Delete]
    Description: DeletionPolicy for S3 bucket

  DynamoDeletionPolicy:
    Type: String
    Default: Delete
    AllowedValues: [Retain, Delete]
    Description: DeletionPolicy for DynamoDB table
  CognitoDeletionPolicy:
    Type: String
    Default: Delete
    AllowedValues: [Retain, Delete]
    Description: DeletionPolicy for Cognito resources

  CognitoUserPoolName:
    Type: String
    Default: QPMSUserPool
    Description: Name of the Cognito User Pool
  CognitoIdentityPoolName:
    Type: String
    Default: QPMSIdentityPool
    Description: Name of the Cognito Identity Pool
  EnableTTL:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable TTL for DynamoDB table

Conditions:
  UseEncryption: !Not [!Equals [!Ref BucketEncryptionType, none]]
  UseKmsEncryption: !Equals [!Ref BucketEncryptionType, aws:kms]
  DeleteEC2: !Equals [!Ref EC2DeletionPolicy, Delete]
  DeleteS3: !Equals [!Ref S3DeletionPolicy, Delete]
  DeleteDynamo: !Equals [!Ref DynamoDeletionPolicy, Delete]
  DeleteCognito: !Equals [!Ref CognitoDeletionPolicy, Delete]
  TTL_Enabled: !Equals [!Ref EnableTTL, "true"]
Resources:
  QPMSDynamoJOBStatusTable:
    Type: AWS::DynamoDB::Table
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteDynamo, Delete, Retain]
    Properties:
      TableName: !Sub 'JobStatusTable-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: object
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: PID
          AttributeType: S 
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
          - IndexName: ByType
            KeySchema:
              - AttributeName: object
                KeyType: HASH
              - AttributeName: status
                KeyType: RANGE  
            Projection:
              ProjectionType: ALL
          - IndexName: ByPID
            KeySchema:
              - AttributeName: PID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
      TimeToLiveSpecification: !If 
        - TTL_Enabled
        - AttributeName: ExpiresAt
          Enabled: true
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: QPMSAppTable

  QPMSDynamoProcessTable:
      Type: AWS::DynamoDB::Table
      Metadata:
        AWS::CloudFormation::DeletionPolicy: !If [DeleteDynamo, Delete, Retain]
      Properties:
        TableName: !Sub 'ProcessLogTable-${AWS::StackName}'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: PID
            AttributeType: S
          - AttributeName: Type
            AttributeType: S
          - AttributeName: CreatedAt
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ByType
            KeySchema:
              - AttributeName: Type
                KeyType: HASH
              - AttributeName: CreatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: ByPID
            KeySchema:
              - AttributeName: PID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification: !If 
          - TTL_Enabled
          - AttributeName: ExpiresAt
            Enabled: true
          - !Ref AWS::NoValue
        Tags:
          - Key: Name
            Value: QPMSProcessTable
  QPMSBackupJobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'BackupJobs-${AWS::StackName}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: orgId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
        - AttributeName: orgId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: OrgStatusIndex
          KeySchema:
            - AttributeName: orgId
              KeyType: HASH
            - AttributeName: status
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Name
          Value: QPMSBackupJobsTable

  QPMSUserPool:
    Type: AWS::Cognito::UserPool
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true

  QPMSUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      ClientName: WebAppClient
      UserPoolId: !Ref QPMSUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - http://localhost:3000/callback
      LogoutURLs:
        - http://localhost:3000/logout
      SupportedIdentityProviders:
        - COGNITO

  QPMSCognitoAuthRole:
    Type: AWS::IAM::Role
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      RoleName: CognitoAuthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref QPMSIdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - dynamodb:GetItem
                Resource: "*"

  QPMSCognitoUnauthRole:
    Type: AWS::IAM::Role
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      RoleName: CognitoUnauthRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref QPMSIdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: unauthenticated
      Policies:
        - PolicyName: CognitoGuestPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Deny
                Action: "*"
                Resource: "*"

  QPMSIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      IdentityPoolName: !Ref CognitoIdentityPoolName
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders:
        - ClientId: !Ref QPMSUserPoolClient
          ProviderName: !GetAtt QPMSUserPool.ProviderName

  QPMSIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteCognito, Delete, Retain]
    Properties:
      IdentityPoolId: !Ref QPMSIdentityPool
      Roles:
        authenticated: !GetAtt QPMSCognitoAuthRole.Arn
        unauthenticated: !GetAtt QPMSCognitoUnauthRole.Arn
  QPMSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, HTTPS, and port 3000
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  QPMSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: EC2AppAccessRole

  QPMSInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref QPMSIAMRole
      InstanceProfileName: EC2AppInstanceProfile

  QPMSEC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteEC2, Delete, Retain]
    Properties:
      ImageId: ami-020cba7c55df1f615
      InstanceType: t2.micro
      IamInstanceProfile: !Ref QPMSInstanceProfile
      SecurityGroupIds:
        - !Ref QPMSSecurityGroup
      Tags:
        - Key: Name
          Value: QPMSEC2WithAccess
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          #aws s3 cp /var/log/user-data.log s3://myapp-bucket-us-east-1-767900165297/logs/user-data.log
          sudo apt update -y

          # ---- SWAP ----
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          swapon --show
          free -h
          echo "/swapfile none swap sw 0 0" | sudo tee -a /etc/fstab
          echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.conf

          # ---- Install base software ----
          curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
          sudo apt install -y nodejs git unzip nginx
          wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
          sudo dpkg -i amazon-cloudwatch-agent.deb
          sudo rm -f amazon-cloudwatch-agent.deb
          npm install -g @salesforce/cli
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          sudo rm -rf aws awscliv2.zip
          npm install -g @aws-sdk/client-s3 @aws-sdk/client-dynamodb @aws-sdk/lib-dynamodb
          npm install -g pm2

          # ---- Clone repo & start app ----
          cd /home/ubuntu
          git clone https://github.com/balu-bunny/Project-BR.git
          cd Project-BR
          npm install
          sudo chown -R ubuntu:ubuntu /home/ubuntu/Project-BR
          chmod -R u+rwX /home/ubuntu/Project-BR
          # ---- Metadata ----
          TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          PUBLIC_DNS=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-hostname)
          REGION=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}')
          echo "Public DNS: $PUBLIC_DNS"
          echo "Region: $REGION"
          #pm2 
          sudo -i -u ubuntu bash <<'EOF'
          cd /home/ubuntu/Project-BR
          pm2 start app.js --name salesforce-backup
          pm2 save
          pm2 startup systemd -u ubuntu --hp /home/ubuntu
          #sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu -k
          #sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu --silent
          #sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
          EOF
          echo 'EOF'
          sudo systemctl enable pm2-ubuntu
          #echo 'systemctl enable pm2-ubuntu'
          sudo systemctl restart pm2-ubuntu
          #echo 'systemctl restart pm2-ubuntu'
          

          # ---- Save env.json ----
          sudo echo '{
            "region": "'$REGION'",
            "userPoolId": "${QPMSUserPool}",
            "userPoolClientId": "${QPMSUserPoolClient}",
            "identityPoolId": "${QPMSIdentityPool}"
          }' > /home/ubuntu/Project-BR/env.json




          # ---- Nginx ----
          cat > /etc/nginx/sites-available/default <<EOF
          server {
              listen 80;
              server_name $PUBLIC_DNS;
              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }
          }
          EOF
          systemctl restart nginx
          systemctl enable nginx
          apt install -y certbot python3-certbot-nginx
          if certbot --nginx --non-interactive --agree-tos --redirect \
          --email balakrishna@qualityze.com \
          -d $PUBLIC_DNS; then
            echo "✅ SSL configured"
          else
              echo "⚠️ Certbot failed, continuing without SSL"
          fi


          # ---- CloudWatch Agent Config ----
          sudo mkdir -p /opt/aws/amazon-cloudwatch-agent/etc
          cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<EOF
          {
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/home/ubuntu/.pm2/logs/salesforce-backup-out.log",
                      "log_group_name": "/Project-BR/pm2/out",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 30
                    },
                    {
                      "file_path": "/home/ubuntu/.pm2/logs/salesforce-backup-error.log",
                      "log_group_name": "/Project-BR/pm2/error",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 30
                    },
                    {
                      "file_path": "/var/log/nginx/access.log",
                      "log_group_name": "/Project-BR/nginx/access",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 14
                    },
                    {
                      "file_path": "/var/log/nginx/error.log",
                      "log_group_name": "/Project-BR/nginx/error",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 14
                    },
                    {
                      "file_path": "/var/log/syslog",
                      "log_group_name": "/Project-BR/system/syslog",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 14
                    },
                    {
                      "file_path": "/var/log/auth.log",
                      "log_group_name": "/Project-BR/system/auth",
                      "log_stream_name": "{instance_id}",
                      "retention_in_days": 14
                    }
                  ]
                }
              }
            }
          }
          EOF

          # ---- Start CloudWatch Agent ----
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config -m ec2 \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
            -s
          sudo systemctl enable amazon-cloudwatch-agent
          sudo systemctl restart amazon-cloudwatch-agent



  QPMSS3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      AWS::CloudFormation::DeletionPolicy: !If [DeleteS3, Delete, Retain]
    Properties:
      BucketName: !Sub "myapp-bucket-${AWS::Region}-${AWS::AccountId}"
      Tags:
        - Key: Name
          Value: QPMSAppBucket
      BucketEncryption: !If
        - UseEncryption
        - ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: !If
                  - UseKmsEncryption
                  - aws:kms
                  - AES256
        - !Ref AWS::NoValue

  CWAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy

  CWInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref CWAgentRole ]


Outputs:
  EC2InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref QPMSEC2Instance

  S3BucketName:
    Description: The name of the created S3 bucket
    Value: !Ref QPMSS3Bucket

  JOBStatusTableName:
    Description: The name of the created DynamoDB table
    Value: !Ref QPMSDynamoJOBStatusTable

  ProcessTableName:
    Description: The name of the created DynamoDB table
    Value: !Ref QPMSDynamoProcessTable

  ScheduledJobTableName:
    Description: The name of the created DynamoDB table
    Value: !Ref QPMSBackupJobsTable

  SecurityGroupId:
    Description: The ID of the security group created for the EC2 instance
    Value: !Ref QPMSSecurityGroup

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref QPMSUserPool

  CognitoUserPoolClientId:
    Description: Cognito User Pool App Client ID
    Value: !Ref QPMSUserPoolClient

  CognitoIdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref QPMSIdentityPool
